name: Deploy to Google Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Google Compute Engine
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        INSTANCE_NAME: ${{ secrets.INSTANCE_NAME }}
        ZONE: ${{ secrets.ZONE }}
      run: |
        gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
        gcloud config set project $PROJECT_ID
        gcloud compute instances update-container $INSTANCE_NAME \
          --zone $ZONE \
          --container-image gcr.io/$PROJECT_ID/discord-character-counter:latest \
          --container-restart-policy on-failure