name: Deploy to Google Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Deploy to Google Compute Engine
      env:
        GCE_PROJECT_ID: ${{ secrets.GCE_PROJECT_ID }}
        GCE_SERVICE_ACCOUNT_KEY: ${{ secrets.GCE_SERVICE_ACCOUNT_KEY }}
        GCE_INSTANCE_NAME: ${{ secrets.GCE_INSTANCE_NAME }}
        GCE_ZONE: ${{ secrets.GCE_ZONE }}
      run: |
        echo "$GCE_SERVICE_ACCOUNT_KEY" > service_account_key.json
        gcloud auth activate-service-account --key-file=service_account_key.json
        gcloud config set project $GCE_PROJECT_ID
        gcloud config set compute/zone $GCE_ZONE
        gcloud compute ssh $GCE_INSTANCE_NAME --command="sudo systemctl stop discord_character_counter"
        gcloud compute scp --recurse . $GCE_INSTANCE_NAME:~/discord_character_counter
        gcloud compute ssh $GCE_INSTANCE_NAME --command="source ~/discord_character_counter/.venv/bin/activate && sudo systemctl start discord_character_counter"
        rm service_account_key.json