name: Deploy to Google Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Authenticate with Google Cloud
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to Google Compute Engine
      run: |
        gcloud compute instances create discord-bot-instance \
          --image-family=ubuntu-2004-lts \
          --image-project=ubuntu-os-cloud \
          --boot-disk-size=10GB \
          --machine-type=e2-micro \
          --metadata-from-file startup-script=deploy/startup_script.sh \
          --scopes=https://www.googleapis.com/auth/cloud-platform \
          --zone=us-central1-a
        gcloud compute firewall-rules create discord-bot-firewall \
          --allow=tcp:80 \
          --network=default \
          --source-ranges=0.0.0.0/0 \
          --target-tags=discord-bot-instance